version-resolver:
  major:
    labels:
      - 'semver:major'
  minor:
    labels:
      - 'semver:minor'
      - 'enhancement'
  patch:
    labels:
      - 'semver:patch'
      - 'bug'
  default: patch

template: |
  # What's Changed
  $CHANGES

categories:
  - title: '🚀 Features'
    labels:
      - 'enhancement'
      - 'semver:minor'
  - title: '🐛 Bug Fixes'
    labels:
      - 'bug'
      - 'semver:patch'
  - title: '⚠️ Breaking Changes'
    labels:
      - 'semver:major'
  - title: '🧰 Maintenance'
    labels:
      - 'maintenance'
  - title: '📝 Documentation'
    labels:
      - 'documentation'
  - title: '📦 Dependency Updates'
    labels:
      - 'dependencies'

exclude-labels:
  - 'skip-changelog'

