name: Auto Close PR
on:
  pull_request_target:
    types: [opened]  # so that not trigger when reopened

permissions:
  pull-requests: write

jobs:
  auto_close_pr:
    runs-on: ubuntu-latest
    if: github.repository == 'gogorichie/terraform-grafana-influxdb-ds-module'
    steps:
      - uses: imba-tjd/auto-close-pr-action@0.3.1
        with:
          pattern: ':\s*confirm\s*-->'
          # message: <optional>
